import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Hello from "./Hello";
import { useState } from "react";
import Panel from "./panel";
import Region from "./Region";
import CatComponent from "./CatComponent";
const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const [ctrl, setCtrl] = useState(true)
  return ( // when we 'return' we are going to render html and our components
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h3>Welcome to my first React Project</h3>
        {/* usually we build a React app with components */}
        {/* It is important to use InitialCap for our own component names */}
        {/* in React, html is always lowercase and React/our stuff is always Initial Cap */}
        <Panel />
        <img src='' alt='' />
        {/* inject a string-literal for 'age' */}
        <Hello username={'Floella'} age={42} />
        {/* conditional rendering */}
        {ctrl && <Hello username={'Ethel'} age={'99'} />}
        <Hello username={'Timnit'} age={'56'} />
        <Hello username={'Ermintrude'} age={'85'} />
        <CatComponent />


      </main>
    </>
  );
}
